[workspace]
authors = ["dyoshyy <d.yoshhyy@gmail.com>"]
channels = ["conda-forge"]
name = "meru"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ftfy = ">=6.3.1,<7"
future = ">=1.0.0,<2"
hydra-core = ">=1.3.2,<2"
loguru = ">=0.7.3,<0.8"
nltk = ">=3.9.1,<4"
scikit-learn = ">=1.6.1,<2"
tensorflow-datasets = ">=4.8.3,<5"
torchmetrics = ">=1.7.1,<2"
tqdm = ">=4.67.1,<5"
ujson = ">=5.10.0,<6"
webdataset = ">=0.2.111,<0.3"
tensorboard = ">=2.18.0,<3"
pip = ">=25.1.1,<26"

[pypi-dependencies]
wordsegment = ">=1.3"
